// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCsuL2aRzkEr2gaJ2XxdHkXb-HgVVDPkQ',
    appId: '1:246426818604:web:df671384198df39c68d989',
    messagingSenderId: '246426818604',
    projectId: 'zoiparilla',
    authDomain: 'zoiparilla.firebaseapp.com',
    storageBucket: 'zoiparilla.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz9DAylvZm0Qjz9pHAXsvce9wGC5fIAyo',
    appId: '1:246426818604:android:5e7c9febc3444da868d989',
    messagingSenderId: '246426818604',
    projectId: 'zoiparilla',
    storageBucket: 'zoiparilla.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeS2dpd80pd35YfBepxZIl3bwsUJ2GLzg',
    appId: '1:246426818604:ios:cba986109e66cb7468d989',
    messagingSenderId: '246426818604',
    projectId: 'zoiparilla',
    storageBucket: 'zoiparilla.appspot.com',
    iosBundleId: 'com.example.zoiparrilla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeS2dpd80pd35YfBepxZIl3bwsUJ2GLzg',
    appId: '1:246426818604:ios:cba986109e66cb7468d989',
    messagingSenderId: '246426818604',
    projectId: 'zoiparilla',
    storageBucket: 'zoiparilla.appspot.com',
    iosBundleId: 'com.example.zoiparrilla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCsuL2aRzkEr2gaJ2XxdHkXb-HgVVDPkQ',
    appId: '1:246426818604:web:e57fa9315941bafc68d989',
    messagingSenderId: '246426818604',
    projectId: 'zoiparilla',
    authDomain: 'zoiparilla.firebaseapp.com',
    storageBucket: 'zoiparilla.appspot.com',
  );
}
